package com.fkhmarketplace.pricing.poc.runtime

import com.fkhmarketplace.pricing.poc.Message;

rule "a runtime sample rule"
when
    m: Message(status == "matched!")
then
    System.out.println("c[_] runtime rule " + m.getStatus());
end


rule "another runtime sample rule"
when
    m: Message(status == "another match!")
then
    System.out.println("runtime drools says " + m.getStatus() + " =^..^=");
end
