
package com.fkhmarketplace.pricing.poc.compiletime

import com.fkhmarketplace.pricing.poc.pojo.Product;
import com.fkhmarketplace.pricing.poc.pojo.Seller;
import com.fkhmarketplace.pricing.poc.pojo.Lot;
import com.fkhmarketplace.pricing.poc.pojo.DiscountInputSignals;
import com.fkhmarketplace.pricing.poc.pojo.DiscountBasePrice;
import com.fkhmarketplace.pricing.poc.operator.Percent;
import com.fkhmarketplace.pricing.poc.rules.DiscountRule;

dialect "java"
rule "for seller_apob_id=seller_location_123 and brand=glaxosmithkline and product_category=Rx set the base price to 20% of MRP"
when
    $p: Product(brand == "glaxosmithkline", category == "Rx")
    $s: Seller(seller_apob_id == "seller_location_123")
    $l: Lot()
    $output: DiscountBasePrice()
then
    update($output)
end
